### PR TITLE
feat: new and updated payload examples with resulting schema changes

### LINKED ISSUE #812: [BUG]: `registry_package` is missing `installation` object
### What happened?

The schema for `registry_package` events (`RegistryPackagePublishedEvent` and `RegistryPackageUpdatedEvent`) are missing the `installation` object.

The documentation lists `installation` as object: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#registry_package

### Versions

`@octokit/webhooks-types@5.8.0` (included with `probot`)
`@octokit/webhooks-types@7.0.3` (latest)

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #812

----

### Before the change?

* The schemas were not up to date with real world payloads

### After the change?

* Updates the schemas to be up to date with real world payloads

### Other information

* Information derived from the OpenAPI spec, and from the example payloads

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Feature/model/API additions: `Type: Feature`

----

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]
How did you go about doing this? How come it wasn't caught by the update script?

**Comment by wolfy1339** [comment]
The update script is broken because of the switch in the GitHub docs to the OpenAPI spec, and because the examples have been removed.

**Comment by wolfy1339** [comment]
I have a webhooks endpoint running on my server that compares incoming webhooks to the schema defined in this repo.

It was originally implemented by @G-Rath, as a serverless function to run on Azure, and I modified it to run on express.

https://github.com/G-Rath/compare-gh-webhook-to-schema-function

**Comment by G-Rath** [comment]
@wolfy1339 fwiw I don't mind migrating the original app to Express/Koa if you like - the serverless function has been shutdown anyway

**Pull request merged**
