### PR TITLE
fix: update `DeleteEvent` schema

### PR DESCRIPTION
**Pull request by reginawang3495**
ref: https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#deleteevent

## Next Steps: 
```
npm run build:schema
npm run build:types
```

### CODE REVIEW

**Comment by wolfy1339** [comment]
Do you have an actual example payload that shows this as true?
The docs aren't 100% accurate, especially when it comes to Webhooks

**Comment by reginawang3495** [comment]
Thanks for the quick review! Not all fields, but yes

```
{
  "id": "18562886179",
  "type": "DeleteEvent",
  "actor": {
    "id": 15240801,
    "login": "dtjanaka",
    "display_login": "dtjanaka",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dtjanaka",
    "avatar_url": "https://avatars.githubusercontent.com/u/15240801?"
  },
  "repo": {
    "id": 103854310,
    "name": "uclaacm/website",
    "url": "https://api.github.com/repos/uclaacm/website"
  },
  "payload": {
    "ref": "jedis-typo",
    "ref_type": "branch",
    "pusher_type": "user"
  },
  "public": true,
  "created_at": "2021-10-22T22:59:22Z",
  "org": {
    "id": 8324381,
    "login": "uclaacm",
    "gravatar_id": "",
    "url": "https://api.github.com/orgs/uclaacm",
    "avatar_url": "https://avatars.githubusercontent.com/u/8324381?"
  }
}
```

**Comment by wolfy1339** [comment]
That's for GitHub events, which are totally different than Webhooks.

We don't yet have any schemas for GitHub events.

**Comment by reginawang3495** [comment]
@wolfy1339 Sorry to bother you, but are you also saying that @octokit doesn't have schemas for GitHub events as a whole as well? 

I did personally look around and couldn't find any either

**Comment by wolfy1339** [comment]
> @wolfy1339 Sorry to bother you, but are you also saying that @octokit doesn't have schemas for GitHub events as a whole as well?

That is correct, we do not have any schemas for GitHub events.
We have some plans to add GitHub Events eventually, https://github.com/octokit/webhooks.js/issues/474

But, Unfortunately the JS octokit libraries no longer have an active maintainer, which means that that is on hold until further notice. I only maintain the webhooks code, and do issue triaging.

You can read about it in [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), subscribe to it for further updates.

**Comment by reginawang3495** [comment]
Ok sounds good, thanks for the info!

**Pull request closed without merging**
