### PR TITLE
refactor: create AlertInstance schema for CodeScaningAlertEvent#alert#instances

### PR DESCRIPTION
**Pull request by wolfy1339**
…#instances

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]
nice!

**Comment by G-Rath** [comment]
er before merging - idk if thats a conventional commit 🤔 

(we should probably check that in CI)

**Comment by G-Rath** [comment]
`refactor` is a valid category - it's the capital letter at the start that I think isn't valid.

**Comment by wolfy1339** [comment]
> er before merging - idk if thats a conventional commit thinking
> 
> (we should probably check that in CI)

I don't think `commitlint` is used here

**Comment by G-Rath** [comment]
> I don't think commitlint is used here

No, but we use semantic-release which... actually that's a good point - it won't error on that sort of thing.

**Comment by oscard0m** [comment]
I think in the past there was [this App](https://github.com/apps/semantic-pull-requests) installed for checking Semantic Commits. On a quick search I did not find anything about it. Did we remove it? @gr2m @wolfy1339

**Comment by G-Rath** [comment]
Personally I've not had a lot of joy with that app, as it means PRs often end up without complete green tickets so the UI makes it look like its not in a good state to be merged.

I pushed up [this branch](https://github.com/octokit/webhooks/tree/add-ci-check-for-conventional-commit) earlier setting up a CI check, which I can PR if people are interested, but we've not had issues so far 🤷 

(The above was me just being forgetful 😅)

**Comment by oscard0m** [comment]
Moved discussion here team 💪🏽 https://github.com/octokit/rest.js/discussions/2018

**Pull request merged**
