### PR TITLE
🤖📯 Octokit webhooks changed

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Comment by wolfy1339** [comment]
GitHub removed the `content_reference` event from the docs, it seems.

**Comment by G-Rath** [comment]
@wolfy1339 what do we need to do to land this?

**Comment by wolfy1339** [comment]
Should be ready to go now

**Comment by wolfy1339** [comment]
On a side note, maybe we should lower the frequency the script runs at. It seems to catch re-renderings that don't affect content a lot of the time

**Review by G-Rath — APPROVED** [review]

**Pull request merged**
