### PR TITLE
fix: documentation URLs updated in event descriptions

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.mdhttps://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]
Clever bot :D

**Comment by wolfy1339** [comment]
We could repurpose the bot to update the schemas if the docs get updated that would fix #257.

**Comment by gr2m** [comment]
> We could repurpose the bot to update the schemas if the docs get updated that would fix #257.

yes, let's do that.

I guess we have to update 

https://github.com/octokit/webhooks/blob/1b1a82ac9687f59feaa0ae5e81f5a1f02dc0ca84/.github/workflows/update.yml#L18

to run `npm run build:all` instead

and update 

https://github.com/octokit/webhooks/blob/1b1a82ac9687f59feaa0ae5e81f5a1f02dc0ca84/.github/workflows/update.yml#L39

we could probably remove the `path` option altogether there

**Comment by gr2m** [comment]
> We could repurpose the bot to update the schemas if the docs get updated that would fix #257.

I'm not sure if it would entirely fix #257 though. If I understand the issue correctly, you'd like to automatically update schemas if the validation of the new payload examples fail against the existing schema? I think for now automated update pull requests such as this will fail and we will have to update the schema manually

**Pull request merged**
