### PR TITLE
fix: use common `PullRequest` interface for `pull_request` events

### PR DESCRIPTION
**Pull request by G-Rath**

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
Tests are failing

**Comment by G-Rath** [comment]
@wolfy1339 I removed the wrong type from a `oneOf` for `ready_for_review` 😅 

On a slightly related sidenote: do you know what the `head` and `base` properties represent? I'm trying to come up with a good name for them:

```
      head: {
        label: 'Codertocat:changes',
        ref: 'changes',
        sha: 'ec26c3e57ca3a959ca5aad62de7213c562f8c821',
        user,
        repo
      },
      base: {
        label: 'Codertocat:master',
        ref: 'master',
        sha: 'f95f852bd8fca8fcc58a9a2d6c842781e32a215e',
        user,
        repo
      },
```

and

```
head: {
  ref: string;
  sha: string;
  repo: RepoRef;
};
base: {
  ref: string;
  sha: string;
  repo: RepoRef;
};
```

**Comment by wolfy1339** [comment]
I think it's related to comparing 2 commits, as in this API: https://docs.github.com/en/rest/reference/repos#compare-two-commits

**Comment by G-Rath** [comment]
Yeah but sadly it doesn't really give a good descriptive name - I guess I'll just go with something like "CommitCompareInfo"

**Comment by wolfy1339** [comment]
I'll look further into it and cross-reference the REST API descriptions

**Comment by wolfy1339** [comment]
Actually, it seems to be when you compare 2 branches together when you create a PR
ie. https://github.com/Codertocat/Hello-World/compare/master...changes
`base` is the branch you want to merge into, `head` is the branch you want to merge (compare to `base`)

**Pull request merged**
