### PR TITLE
feat: Update schemas with better types and use common schemas

### PR DESCRIPTION
**Pull request by wolfy1339**
Sorry @G-Rath :sweat_smile:
I went around all the schemas and have used the common schemas everywhere it could be used instead of defining it manually.
I also checked my webhooks that are getting sent to the validator and have updated the schemas with the required fixes

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Comment by G-Rath** [comment]
@wolfy1339 ugh you're killing me 😭😂

Could we land #252 after this one so I don't have to do any more major rebasing? 🙏😅

(I've got a few cool deduplication scripts primed once the new structure is landed)

**Review by G-Rath — APPROVED** [review]

**Comment by wolfy1339** [comment]
> Could we land #252 after this one so I don't have to do any more major rebasing? :pray::sweat_smile:

Yes of course

> (I've got a few cool deduplication scripts primed once the new structure is landed)

That will be useful

**Comment by oscard0m** [comment]
> @wolfy1339 ugh you're killing me 😭😂
> 
> Could we land #252 after this one so I don't have to do any more major rebasing? 🙏😅
> 
> (I've got a few cool deduplication scripts primed once the new structure is landed)

Another reason for smaller PR's 🙈

**Comment by G-Rath** [comment]
> Another reason for smaller PR's 🙈

Sadly it's not really possible to make the PR much smaller, as it's a bunch of file moves which are always painful to rebase :)

> That will be useful

Very! I've got a script that looks through all the schemas and replaces *any* object that matches a `common` schema with a reference to said common schema, meaning that we can deduplicate on mass by just creating new common schemas.

Should also make it easier to contribute new schemas as you can just add a single schema and then run the script to have it figure out if there are common references to use 😍

So we'll just be left with the hardest task of them all: figuring out what to name the common schemas 😂

I'll land it after we've got #252 landed

**Comment by gr2m** [comment]
>  I've got a script that looks through all the schemas and replaces _any_ object that matches a `common` schema with a reference to said common schema, meaning that we can deduplicate on mass by just creating new common schemas.
> 
> Should also make it easier to contribute new schemas as you can just add a single schema and then run the script to have it figure out if there are common references to use 😍

That sounds super dope!

**Comment by gr2m** [comment]
> So we'll just be left with the hardest task of them all: figuring out what to name the common schemas 😂

We might get some inspiration from GitHub's Official OpenAPI spec: https://github.com/github/rest-api-description/. I think the OpenAPI spec folks are working on integrating webhooks into OpenAPI, so eventually GitHub might merge the schemas for webhooks into the existing OpenAPI spec. That would also permit to reuse schemas which makes a lot of sense I think. 

Don't worry about it if it makes things harder, we can worry about it in the future. It's a problem when it's a problem :) But I thought I'd mention it. If it makes no big difference, it would be nice to align with the naming conventions and structure of the existing OpenAPI spec schema components

**Comment by G-Rath** [comment]
> That sounds super dope!

@gr2m it is pretty cool (if I do say so myself) - we're just waiting on your approve to land #252, so if you're happy for that PR to be merged, I can start making PRs with that script.

> Don't worry about it if it makes things harder, we can worry about it in the future.

I'll have a look over and see if there are common names, but yeah it won't be a blocker - renaming is super easy to do.

**Comment by gr2m** [comment]
> btw, it's not tied to this repo in any particular way, so it should be usable for other json schemas, including the ones in `rest-api-description`. It'd need some slight modification as currently it's file based, but making it single-schema based would be pretty easy. Happy to help if you'd like to explore applying this to other repos :)

Maybe create an issue on https://github.com/github/rest-api-description when you can run your script against it. The setup for this repo is rather complicated, but filing an issue might be helpful, they can decide what they want to do with it.

**Pull request merged**
