### PR TITLE
feat: new `pull_request_review_thread` event

### LINKED ISSUE #593: pull_request_review_thread types are missing
Here's what we hacked, please add it to the repo. Thanks!

```ts
// not implemented yet
// import { PullRequestReviewThreadResolvedEvent } from '@octokit/webhooks-types';
import { SimplePullRequest, Repository, Organization, User, PullRequestReviewComment } from '@octokit/webhooks-types';

export interface Thread {
  node_id: string;
  comments: PullRequestReviewComment[];
}

export interface PullRequestReviewThreadResolvedEvent {
  action: "resolved",
  pull_request: SimplePullRequest;
  thread: Thread;
  repository: Repository;
  organization: Organization;
  sender: User;
}

export interface PullRequestReviewThreadUnresolvedEvent {
  action: "unresolved",
  pull_request: SimplePullRequest;
  thread: Thread;
  repository: Repository;
  organization: Organization;
  sender: User;
}
```

### PR DESCRIPTION
**Pull request by wolfy1339**
Fixes #593

This event is currently not documented in the GitHub docs

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]
ugh thank you! I'd been meaning to do this for a while but hadn't gotten the time :(

**Comment by wolfy1339** [comment]
Ah shucks!

Why isn't the `Do types need to be regenerated?` check required?

**Comment by G-Rath** [comment]
hmm I thought it was?

**Comment by G-Rath** [comment]
oh you mean for merging - idk about that 😅

**Pull request merged**
