### PR TITLE
refactor(update-webhooks): adapt for new header layout of docs & update cache

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by wolfy1339 — CHANGES_REQUESTED** [review]
Payload update script seems to need an update. They changed headers type

**Comment by wolfy1339** [comment]
The docs for `GHES-219` and `GHES-220` don't use the updated format.
Because of that the modifications needed to make it work for the other versions break those 2 versions.

**Comment by gr2m** [comment]
> The docs for `GHES-219` and `GHES-220` don't use the updated format.
> Because of that the modifications needed to make it work for the other versions break those 2 versions.

shall we just remove these?

**Comment by wolfy1339** [comment]
> shall we just remove these?

Sounds reasonable

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
