### PR TITLE
fix: update the pull_request property in `WorkflowRun` with the pull_request schema

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by ADIK171191** [comment]
request

**Review by ADIK171191 — CHANGES_REQUESTED** [review]
changes @ADIK171191

**Comment by ADIK171191** [comment]
@ADIK171191

**Comment by ADIK171191** [comment]
@ADIK171191

**Review by gr2m — APPROVED** [review]
Looks good to me 👍🏼

**Pull request merged**
