### PR TITLE
feat: always have examples with requested_reviewers

### PR DESCRIPTION
**Pull request by christophehurpeau**
Related to octokit/webhooks.js#293

This ensure all "requested_reviewers" array are typed

It however doesn't make sense that the creator is the same as the requested_reviewer, is there another example user I could use ?

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Oups, I'll fix the conflicts

**Comment by gr2m** [comment]
> It however doesn't make sense that the creator is the same as the requested_reviewer, is there another example user I could use ?

Maybe https://api.github.com/users/octocat?

**Comment by christophehurpeau** [comment]
@gr2m yes thanks ! updated with that user :)

**Review by gr2m — APPROVED** [review]
Thanks a lot!

**Pull request merged**
