### PR TITLE
feat: always have examples with assignees

### PR DESCRIPTION
**Pull request by christophehurpeau**
Related to https://github.com/octokit/webhooks.js/issues/293

This ensure all "assignees" array are typed

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Awesome, thanks a lot!

**Review by gr2m — CHANGES_REQUESTED** [review]
sorry it seams that `index.json` is out of sync with the examples. You can run `node bin/octokit-webhooks.js update --cached` to spot the differences. Could you please have a look?

**Comment by christophehurpeau** [comment]
@gr2m yes thanks for the command ! I think it would be great to add it in CONTRIBUTING.md :)
However I don't quite understand why there is some some `"assignees": []` back ? is there generation from something ouside payload-examples ?

**Comment by christophehurpeau** [comment]
Is that ok if I make a PR for each field or should I do one big PR ?

**Comment by gr2m** [comment]
> I think it would be great to add it in CONTRIBUTING.md :)

Very good idea 👍🏼 

> Is that ok if I make a PR for each field or should I do one big PR ?

Of course! I'll merge this PR in, and then you can do follow up PRs as you see fit

**Review by gr2m — APPROVED** [review]

**Pull request merged**
