### PR TITLE
feat: create `Link` interface

### PR DESCRIPTION
**Pull request by G-Rath**
It's a small one, but still nice to have since they should all be the same format etc

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]
It's also like this in the REST API OpenAPI schema

**Comment by G-Rath** [comment]
```
❌ Payload 'pull_request/assigned.payload.json' does not match schema
[
  {
    keyword: 'format',
    dataPath: '/pull_request/_links/review_comment/href',
    schemaPath: 'link.schema.json/properties/href/format',
    params: { format: 'uri' },
    message: 'should match format "uri"'
  },
  ```

Interesting...

**Comment by G-Rath** [comment]
@wolfy1339 seems that `href` doesn't have to confirm to uri format, since it can be "https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}" which is not a valid uri.

**Comment by wolfy1339** [comment]
I noticed that I'm many places when adding those in

**Comment by G-Rath** [comment]
It's because it should `uri-template` format instead :)

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
