### PR TITLE
feat: create `Milestone` common schema

### PR DESCRIPTION
**Pull request by G-Rath**
Technically this changes the schema for a bunch of schemas, but I'm 99% sure that all instances of milestone can `null` for `closed_at`, and that our payload examples don't include ones with closed milestones for all the schemas that didn't have it marked as `string | null` (about half or so).

### CODE REVIEW

**Comment by wolfy1339** [comment]
It seems that you are missing `common/milestone.schema.json`

**Comment by G-Rath** [comment]
Yeah, I keep forgetting to `git add` the extracted schemas 😅

**Comment by wolfy1339** [comment]
> I'm 99% sure that all instances of milestone can `null` for `closed_at`, and that our payload examples don't include ones with closed milestones for all the schemas that didn't have it marked as `string | null` (about half or so).

If you look at the `milestone` event, you'll see some with the `closed_at` property as a string. Those ones, should stay as-is IMO, better to be explicit than to save lines of code

**Comment by G-Rath** [comment]
> If you look at the milestone event, you'll see some with the closed_at property as a string.

I think the only one that applies to is the `closed` event - I'll revert that one shortly.

(I've actually got a cunning plan anyway on how to do `extends` in the types 😉)

**Review by oscard0m — APPROVED** [review]

**Comment by wolfy1339** [comment]
> > If you look at the milestone event, you'll see some with the closed_at property as a string.
> 
> I think the only one that applies to is the `closed` event - I'll revert that one shortly.
> 
> (I've actually got a cunning plan anyway on how to do `extends` in the types wink)

Have you gotten around to this?

**Comment by G-Rath** [comment]
> Have you gotten around to this?

No yet sorry 😓

**Comment by G-Rath** [comment]
I'm going to close this due to the rebase conflicts and I think it'll be easier to start again.

Someone else can pick this up if they like, otherwise I'll get back to it eventually :)

**Pull request closed without merging**
