### PR TITLE
build: fix scripts Node 20 compat

### LINKED ISSUE #862: [MAINT]: Release is failing
### Describe the need

```
ts-node --esm -T bin/octokit-schema.mts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".mts" for /home/runner/work/webhooks/webhooks/bin/octokit-schema.mts
```

https://github.com/octokit/webhooks/actions/runs/6845309525/job/18610328638#step:5:9

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wolfy1339**
This is an issue with how ts-node hooks into the import process due to a breaking change made in NodeJS 20.
 See https://github.com/TypeStrong/ts-node/issues/1997 for more details

Resolves #862

----

### Before the change?

* 

### After the change?

* 

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by wolfy1339** [comment]
I have tested this on both NodeJS v18 and v20 and it fixes the issue

**Review by gr2m — APPROVED** [review]
cheers!

**Comment by gr2m** [comment]
hmm did you miss one? Tests are still failing

**Comment by wolfy1339** [comment]
I'm looking into it.

**Pull request merged**
