### PR TITLE
🤖📯 Octokit webhooks changed

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).
If there are any new events added, follow the [steps outlined](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#creating-a-new-schema) in order to create the required schemas.
If there were only description updates, or new properties added, simply modify the appropriate schemas and commit them to this PR. Don't forget to generate the types as well.

### CODE REVIEW

**Comment by wolfy1339** [comment]
There's a new event `installation_target`

**Comment by wolfy1339** [comment]
And the docs changed formats which explains the large diff

**Comment by kfcampbell** [comment]
I'm unsure why the "test" check is consistently showing as expected but it doesn't seem like it's ever executing.

**Comment by wolfy1339** [comment]
It's a bug that we can't seem to figure out why it happens. It's a regular occurrence.

When this happens pushing an empty commit makes the workflows execute as they should

**Comment by kfcampbell** [comment]
TIL, thanks @wolfy1339! Looks like the builds are all happily green now.

**Comment by kfcampbell** [comment]
Hmm...I meant to merge this before the conflict, and I totally forgot about it. Perhaps at this point it's worth closing and waiting for the PR to be recreated?

**Comment by wolfy1339** [comment]
> Perhaps at this point it's worth closing and waiting for the PR to be recreated?

I agree :+1: 

there are some issues that need to be considered, the format of the docs has changed significantly and results in missing information when the `payload-examples/api.github.com/index.json` is regenerated

**Pull request closed without merging**
