### PR TITLE
fix(payload-examples): Add missing "organization" object

### PR DESCRIPTION
**Pull request by wolfy1339**
Adds the missing organization object in multiple events.
Ref: octokit/webhooks.js#87

### CODE REVIEW

**Review by dominguezcelada — APPROVED** [review]

**Review by gr2m — CHANGES_REQUESTED** [review]
Unfortunately, we cannot just add `organization` to the existing payloads, because it woudl imply that it's always present which is not the case. 

> Webhook payloads contain the organization object when the webhook is configured for an organization or the event occurs from activity in a repository owned by an organization.

https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-common-properties

Instead, we have to create additional payload examples, e.g. copy `payload-examples/api.github.com/check_run.completed.payload.json` into sth like `payload-examples/api.github.com/check_run.completed.with-organization.payload.json`. Because the property will be present in one payload but not the other, the resulting types will make the `organization` property optional

**Comment by wolfy1339** [comment]
Got it :+1: . Will do that and re-push

**Comment by wolfy1339** [comment]
@gr2m I can't seem to update the `index.json` file anymore, it errors out.
```
Error: https://github.com/github/docs/edit/main/content/developers/webhooks-and-events/webhook-events-and-payloads.md has no #anchor hash
```

**Review by dominguezcelada — APPROVED** [review]

**Comment by gr2m** [comment]
> @gr2m I can't seem to update the `index.json` file anymore, it errors out.
> 
> ```
> Error: https://github.com/github/docs/edit/main/content/developers/webhooks-and-events/webhook-events-and-payloads.md has no #anchor hash
> ```

I just fixed that a moment ago, via #185

**Review by gr2m — APPROVED** [review]
Looks good to me 👍🏼 Maybe it would make sense to rephrase the commit message to something like

> feat(examples): event payloads with organization key

I'll leave it up to you, ship at your convenience :)

**Pull request merged**
