### PR TITLE
feat: add `workflow_job` schema

### PR DESCRIPTION
**Pull request by G-Rath**
I've taken some liberties with `steps` in terms of being strict on the number of items - I think it work and be fine, but wouldn't be surprised if we later find a payload with more items for an `in_progress` 🤷

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
👍🏼

**Comment by wolfy1339** [comment]
Looks like you forgot to generate `index.json`

**Comment by gr2m** [comment]
> Looks like you forgot to generate `index.json`

can we enforce it somehow as part of the CI?

**Comment by wolfy1339** [comment]
It can be done easily. There's already a `--check` flag implemented.

**Comment by G-Rath** [comment]
Yeah I thought we already did check it in CI - maybe it got lost in the shuffle when we split the monopackage up?

**Comment by wolfy1339** [comment]
I don't think there was ever a check for the examples

**Comment by npalm** [comment]
Looks like that the job status `queued` is missing

**Comment by gr2m** [comment]
can you file a dedicated issue if the schemas/types are not complete?

**Pull request merged**
