### PR TITLE
feat: new `workflow_run.in_progress` and `dependabot_alert` events, `submitted_at` can be `null` in `PullRequestReviewEvent`

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).
If there are any new events added, follow the [steps outlined](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#creating-a-new-schema) in order to create the required schemas.
If there were only description updates, or new properties added, simply modify the appropriate schemas and commit them to this PR. Don't forget to generate the types as well.

### CODE REVIEW

**Review by nickfloyd — APPROVED** [review]
LGTM! ❤️

**Comment by wolfy1339** [comment]
I added schemas for the `dependabot_alert` event, they were missed in a previous PR

**Comment by gr2m** [comment]
@wolfy1339 sorry I assumed you were done because you requested the review and removed the WIP from the title. Can you put it back if you are still working on it?

**Comment by wolfy1339** [comment]
I believe it's good now

**Comment by wolfy1339** [comment]
@nickfloyd Can you re-review this?

**Review by nickfloyd — APPROVED** [review]
LGTM! ❤️

**Pull request merged**
