### PR TITLE
fix: correct typo in payload examples for `discussion` event

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes on [GitHub’s Webhooks Event Types & Payloads](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads) and want to let you know about it 👋🤖

I can't tell if the changes are fixes, features or breaking changes. You'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/webhooks/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by wolfy1339 — CHANGES_REQUESTED** [review]
This change doesn't seem right

**Comment by gr2m** [comment]
> This change doesn't seem right

looks like the `withdrawn` action for the `security_advisory` event was removed from all current GHES, it probably does not exist in these versions. 

It is still documented at https://docs.github.com/en/enterprise-server@3.1/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#security_advisory, maybe the change was reverted?

**Comment by wolfy1339** [comment]
> looks like the `withdrawn` action for the `security_advisory` event was removed from all current GHES, it probably does not exist in these versions.

It was also removed from `api.github.com` docs

> It is still documented at https://docs.github.com/en/enterprise-server@3.1/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#security_advisory, maybe the change was reverted?

The change doesn't seem to be reverted in the public docs repo.

**Comment by gr2m** [comment]
> The change doesn't seem to be reverted in the public docs rep

If `withdrawn` is still in the docs, shouldn't the automated update bring it back in this PR?

**Comment by wolfy1339** [comment]
> If `withdrawn` is still in the docs, shouldn't the automated update bring it back in this PR?

It should. It seems the docs layout has changed again

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
